import { isRtlLanguage, normalizeLanguage, type SupportedLanguage } from './i18n';
export type QdnTheme = 'light' | 'dark'; export type QdnUiStyle = 'classic' | 'modern';
export type QdnDisplaySettings = { language: SupportedLanguage; theme: QdnTheme; uiStyle: QdnUiStyle };
const defaults: QdnDisplaySettings = { language: 'en', theme: 'light', uiStyle: 'classic' };
const theme = (value: unknown): QdnTheme | null => typeof value === 'string' && ['light', 'dark'].includes(value.toLowerCase()) ? value.toLowerCase() as QdnTheme : null;
const style = (value: unknown): QdnUiStyle | null => typeof value === 'string' && ['classic', 'modern'].includes(value.toLowerCase()) ? value.toLowerCase() as QdnUiStyle : null;
export function getInitialDisplaySettings(): QdnDisplaySettings { const query = typeof window === 'undefined' ? null : new URLSearchParams(window.location.search); return { theme: theme(query?.get('theme') ?? window?._qdnTheme) ?? defaults.theme, uiStyle: style(query?.get('uiStyle') ?? query?.get('ui-style') ?? window?._qdnUiStyle ?? window?._qdnUIStyle) ?? defaults.uiStyle, language: normalizeLanguage(query?.get('lang')) ?? defaults.language }; }
export function applyDisplaySettings(settings: QdnDisplaySettings) { if (typeof document === 'undefined') return; const root = document.documentElement; root.dataset.theme = settings.theme; root.dataset.ui = settings.uiStyle; root.lang = settings.language; root.dir = isRtlLanguage(settings.language) ? 'rtl' : 'ltr'; root.style.colorScheme = settings.theme; }
export function updateFromHostMessage(data: unknown, current: QdnDisplaySettings): QdnDisplaySettings | null { if (!data || typeof data !== 'object') return null; const item = data as Record<string, unknown>; if (item.requestedHandler && item.requestedHandler !== 'UI') return null; if (!['THEME_CHANGED', 'UI_STYLE_CHANGED', 'DISPLAY_SETTINGS_CHANGED', 'LANGUAGE_CHANGED'].includes(String(item.action))) return null; return { theme: theme(item.theme ?? item.qdnTheme) ?? current.theme, uiStyle: style(item.uiStyle ?? item.ui ?? item.qdnUiStyle ?? item.qdnUIStyle) ?? current.uiStyle, language: normalizeLanguage(item.language ?? item.lang ?? item.qdnLang) ?? current.language }; }
